---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress@sha256:5ab0b268e8652327e1258d1d9dad93444a0811359bb56557d2f4b1aca81a1bc6

          ports:
            - containerPort: 80
