---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress@sha256:7bba77a3e910278f44072a8e59168d35e0c493afc5f4f729cd2a8a98ebc593f3

          ports:
            - containerPort: 80
