---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress@sha256:8580f9c5b63db9fb1aeb22b0411e13345e754f98f12473f920d52e7487d6aca6

          ports:
            - containerPort: 80
